### ISSUE TITLE
trailing space in query => filter matches all

### ISSUE THREAD

**Issue by brendano** [plasma-umass/Apply2#75]
This seems to work, returning 5 records.  Not with the double parens.

((areas ~ social))

This does not, returning the full set (1264 records).  It has a trailing space compared to the previous query.

((areas ~ social ))

**Comment by brendano** [comment]
actually, i think if there's an error in the query it always returns all.  for example, I keep forgetting whether it's "area" or "areas".  if i do the wrong one, then it returns all which is pretty slow at least on my browser/machine.  if it just said there was an error without trying to run the query, then i could easily debug the query (and it doesnt even have to say what the error is, just that there was a query parse error)

**Comment by arjunguha** [comment]
both are bugs. i'll fix

**Comment by etosch** [comment]
re: typos in column tokens -- I think it would be helpful to have a tooltip that shows the token associated with the column.

**Comment by brendano** [comment]
looks fixed to me!
