### ISSUE TITLE
"400 Bad Request", no pages work

### ISSUE THREAD

**Issue by brendano** [plasma-umass/Apply2#76]
all pages currently are getting for me

Bad Request

Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Cookie
Apache/2.4.7 (Ubuntu) Server at admitreview.cs.umass.edu Port 443

However, if I open an incognito window and log back in, it works.

**Comment by arjunguha** [comment]
whacky. i'll investigate. could you just clear cookies for the admitreview.cs.umass.edu domain? that should fix it

**Comment by arjunguha** [comment]
@brendano did my suggestion work? (Clearing cookies for that domain.)

**Comment by brendano** [comment]
i'm no longer getting the error so not sure.  incognito def helps.

**Comment by arjunguha** [comment]
I'm closing this for now.

**Comment by brendano** [comment]
it happened again and clearing the admitreview.cs.umass.edu cookie did indeed fix it.  so did incognito mode.  so basically it's not worth worrying about this bug since the workaround is good

i wonder if it's because i used a series of queries and fairly long ones.  the one that it broke on was the following, though it certainly can run this one fine now.

```
(faculty~wallach || faculty~mccallum || faculty = "Brendan O'Connor") && program~phd && new-gre-verbal > 150
```
