### ISSUE TITLE
initial load time on firefox isn't great

### ISSUE THREAD

**Issue by etosch** [plasma-umass/Apply2#77]
I frequently get this message:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://admitreview.cs.umass.edu/js/jquery.dataTables.min.js:98

especially when I accidentally navigate away and then return.

**Comment by arjunguha** [comment]
use chrome

**Comment by arjunguha** [comment]
More seriously, I'll take a look when I return, since it Works For Me.

**Comment by etosch** [comment]
Hm, okay. I’ll do more serious testing later today, on both my laptop and my desktop. Maybe I just had too many tabs open...

**Comment by etosch** [comment]
btw, tried on the desktop with a fresh firefox, still getting a notice asking me if i want to continue on this page, slow loading, etc.
