### ISSUE TITLE
Add to filter documentation: Search for unrated applicants

### ISSUE THREAD

**Issue by mcorner** [plasma-umass/Apply2#98]
I can do this: !(rating(Corner) >= 1), but that only gets people not rated by me.  For MS admissions we are doing one review per person, so I want "rating is null"

**Comment by brunyuriy** [comment]
I believe !(rating("") >= 1)
is your answer

**Comment by mcorner** [comment]
Oh, that is very good.   I have thusly changed the title of this bug to document that...

**Comment by arjunguha** [comment]
What if I give you guys wiki-page edit access?

**Comment by mcorner** [comment]
Yeah, I bet there are other tips/tricks that we can share.

**Comment by arjunguha** [comment]
BTW, can't you guys edit the wiki page when you're logged in to Github? Isn't that how wiki's work?

https://github.com/plasma-umass/Apply2/wiki/Filtering-Applications

**Comment by mcorner** [comment]
Well look at that.  Done.
